export const USER_CONSTANTS = {
  SET_USER_DATA: 'SET_USER_DATA',
  GET_USER_DATA: 'GET_USER_DATA',
};

export const INDIVIDUAL_EXPENSE_CONSTANTS = {
  ADD_INDIVIDUAL_EXPENSE_DATA: 'ADD_INDIVIDUAL_EXPENSE_DATA',
};

export const GROUP_EXPENSE_CONSTANTS = {
  ADD_GROUP_EXPENSE_DATA: 'ADD_GROUP_EXPENSE_DATA',
  CREATE_GROUP: 'CREATE_GROUP',
};
