const SplitUpStrings = {
  ADD: 'Add',
  ADD_DETAILS: 'Add Details',
  ADD_DETAILS_MODAL: 'Add Details Modal',
  ADD_GROUP_MEMBERS: 'Add Group Members',
  ADD_EXPENSE: 'Add an Expense',
  CLOSE: 'Close',
  CREATE: 'Create',
  CREATE_GROUP: 'Create a Group',
  DIVIDE: 'Divide',
  DIVIDE_EQUALLY: 'Equally',
  DIVIDE_UNEQUALLY: 'Unequally',
  FIELD_EMPTY_ERROR: ' *Field is Empty',
  GROUP: 'GROUP',
  GROUP_MEMBERS: 'Total Members',
  GROUP_MEMBER_NAMES: 'Member Names',
  GROUP_NAME: 'Group name',
  INDIVIDUAL: 'INDIVIDUAL',
  MENU_STRING_INDIVIDUAL: 'Individual',
  MENU_STRING_GROUPS: 'Groups',
  MENU_STRING_ACTIVITIES: 'Activities',
  NO_RECORDS_FOUND: `You have not created any record please click on '+' button to create a record`,
  PAID_BY: 'Paid by',
  TOTAL_AMOUNT: 'Total Amount',
};

export default SplitUpStrings;
